config/routes.rb
Rails.application.routes.draw do
  root to: 'opinions#index'

  resources :users, except: :destroy

  resources :opinions, only: %i[index create] do
    resources :comments, only: [:create]
  end

  post '/user/:id/follow', to: 'followings#create', as: 'follow'
  delete '/user/:id/unfollow', to: 'followings#destroy', as: 'unfollow'

  # get '/user/:id', to: 'users#show', as: 'user'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :opinion

  validates :text, presence: true, length: { minimum: 4, maximum: 100 }
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  validates :text, presence: true, length: { minimum: 4, maximum: 300 }

  scope :most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :opinions, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :photo
  has_one_attached :cover_image

  has_many :followings, class_name: 'Following', foreign_key: 'follower_id'
  has_many :followeds, through: :followings, source: :followed

  has_many :inverse_followings, class_name: 'Following', foreign_key: 'followed_id'
  has_many :followers, through: :inverse_followings, source: :follower

  validates :username, presence: true, uniqueness: true, length: { minimum: 4, maximum: 20 }
  validates :fullname, presence: true, length: { minimum: 6, maximum: 30 }

  validates :photo, presence: true

  def who_to_follow
    User.where.not(id: id).where.not(id: followeds).order('created_at DESC').limit(10)
  end

  after_commit :add_default_cover, on: :create

  private

  # rubocop:disable Style/GuardClause
  def add_default_cover
    unless cover_image.attached?
      cover_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default-cover.jpg')),
                         filename: 'default-cover.jpg', content_type: 'image/jpg')
    end
  end
  # rubocop:enable Style/GuardClause
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def require_sign_in
    redirect_to sign_in_path, alert: 'Please sign in.' unless current_user
  end

  def redirect_to_root_path
    redirect_to root_path, alert: 'You already signed in.' if current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.opinion_id = params[:opinion_id]
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
    else
      flash[:alert] = 'Something went wrong.'
    end
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    @followed = User.find(params[:id])
    @following = current_user.followings.new(followed_id: @followed.id)
    if @following.save
      flash[:notice] = "You started following #{@followed.fullname}"
    else
      flash[:alert] = 'Something went wrong ...'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @user_to_unfollow = User.find(params[:id])
    following = current_user.followings.where(followed_id: @user_to_unfollow.id)[0]
    following.destroy
    if following
      flash[:notice] = "You unfollowed #{@user_to_unfollow.fullname}"
    else
      flash[:alert] = 'It was not possible to remove this friendship. Try again later.'
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :require_sign_in

  def index
    @opinion = Opinion.new
    @opinions = Opinion.includes(:comments).most_recent.limit(20)
    @who_to_follow = current_user.who_to_follow
  end

  def create
    @opinion = current_user.opinions.build(opinion_params)
    if @opinion.save
      flash[:notice] = 'Opinion was created successfully'
    else
      flash[:alert] = 'Something went wrong...'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def opinion_params
    params.require(:opinion).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_to_root_path, only: %i[new create]

  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user
      session[:user_id] = @user.id
      flash[:notice] = 'User successfully logged in.'
      redirect_to root_path
    else
      flash.now[:alert] = 'Something went wrong...'
      render :new
    end
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
      flash[:notice] = 'You have successfully logged out'
    else
      flash[:notice] = 'Something went wrong...'
    end
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_sign_in, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Account is created.'
      redirect_to root_path
    else
      flash[:alert] = 'Account is not created. Something went wrong.'
      render new_user_path
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      flash[:notice] = 'User was successfully updated'
      redirect_to @user
    else
      flash[:alert] = 'Something went wrong'
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @opinion = Opinion.new
    @opinions = @user.opinions.includes(:comments).most_recent.limit(20)
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_notice_and_alert
    if notice.present?
      content_tag(:span, notice, class: 'notice bg-success')
    elsif alert.present?
      content_tag(:span, alert, class: 'alert bg-warning')
    end
  end

  def show_navbar
    render '/shared/navbar' if logged_in?
  end

  def show_header
    render '/shared/header' if logged_in?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
  def followings_button(user)
    return nil unless current_user.id != user.id

    if current_user.followeds.include?(user)
      link_to '-', unfollow_path(user), method: :delete, class: 'unfollow-btn'
    else
      link_to '+', follow_path(user), method: :post, class: 'follow-btn'
    end
  end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
  def show_comments_title(opinion)
    content_tag(:h4, 'All comments:') if opinion.comments.present?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def last_follower(user)
    res = ''
    if user.followers.any?
      follower = user.followers.last
      res = 'Followed by ' + link_to(follower.fullname, user_path(follower.id))
    else
      res = 'No followers'
    end
    res.html_safe
  end

  def show_errors(object)
    object.errors.full_messages[0].html_safe if object.errors.any?
  end

  def show_followers
    if @user.followers.none?
      content_tag(:p, 'NO FOLLOWERS')
    else
      render '/shared/followers'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>RorCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="container">
        <div class="row notice-and-alert text-center">
            <%= show_notice_and_alert %>
        </div>
        <div class="row">
            <%= show_navbar %>
            <main class="col m-0">
                <%= show_header %>
                <div class="container">
                    <div class="row">
                        <%= yield %>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>

</html>

app/views/opinions/_opinion.html.erb
<div class="d-flex mt-3">
<%= image_tag opinion.author.photo %>
<div class="content ml-2">
  <div class="main-content">
    <span><%= link_to opinion.author.fullname, user_path(opinion.author.id), class: "author" %></span><br>
    <span class="tweet-text"><%= opinion.text %></span>
  </div>

  <div class="comment-section mt-2">
    <%= show_comments_title(opinion) %>
    <% opinion.comments.each do |comment| %>
      <div class="comment-content my-1">
          <%= image_tag comment.user.photo %>
          <span class="comment-author">@<%= link_to comment.user.username, user_path(comment.user.id) %>:</span>
          <span class="comment-date"> at <%= comment.created_at.strftime("%Y/%m/%d") %>: </span>
          <span class="comment-text"><%= comment.text %></span>
      </div>
      <% end %>
  </div>

  <%= form_for(opinion.comments.new, url: opinion_comments_path(opinion)) do |form| %>
    <div class="form-group">
      <%= form.text_field :text, id: :comment_text, class: "form-control", placeholder: 'Add comment' %>
    </div>
    <%= form.submit 'Comment', class: "d-none" %>
  <% end %>
</div>
</div>

app/views/opinions/index.html.erb
<div class="opinions-section col-9">
  <div class="opinions-nav">
    <a href="#">TWEETS</a>
  </div>

  <%= form_for(@opinion, html: { class: "tweet-form rounded mt-4 p-3" }) do |f| %>
    <h3 class="mb-3">TWEET SOMETHING</h3>
    <div class="form-group">
    <%= f.text_field :text, class: "form-control", autofocus: true, placeholder: "Compose your tweet..." %>
    </div>
    <%= f.submit class: "d-none"%>
  <% end %>

  <div class="tweet-feed rounded mt-3 p-3">
    <h3 class="pb-3">ALL TWEETS</h3>
    <%= render @opinions %>
  </div>
</div>

<div class="right-section col">
  <div class="who-to-follow">
    <h3>WHO TO FOLLOW</h3>
    <div class="who-to-follow-content mt-4">
      <%= render @who_to_follow %>
    </div>
  </div>
</div>

app/views/shared/_followers.html.erb
<% @user.followers.each do |follower| %>
  <div class="followed-by-person d-flex align-items-center my-1">
    <%= image_tag follower.photo, class: "mr-1" %>
    <div>
      <%= link_to follower.fullname, user_path(follower.id), class: "followed-by-fullname" %>
      <span>@<%= follower.username %></span>
    </div>
    <%= followings_button(follower) %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="d-flex justify-content-between align-items-center">
    <%= link_to root_path, class: "header-left" do %>
    <%= fa_icon "twitter" %>
    <% end %>
    <%= link_to edit_user_path(current_user), class: "header-right" do %>
    <%= fa_icon "cog" %>
    <% end %>
</header>

app/views/shared/_navbar.html.erb
<nav class="col-3">
    <div class="photo-and-name d-flex align-items-center mx-2">
        <%= image_tag current_user.photo, class: "mr-2" %>
        <%= link_to current_user.fullname, user_path(current_user.id) %>
    </div>
    <div class="nav-counter d-flex flex-wrap justify-content-around">
        <span class="text-center"><%= current_user.followeds.count %><br>Following</span>
        <span class="text-center"><%= current_user.followers.count %><br>Followers</span>
    </div>
    <div class="nav-links text-left m-2">
        <%= link_to root_path, class: "d-block"  do %>
        <%= fa_icon "home" %>
        <span>HOME</span>
        <% end %>
        <%= link_to user_path(current_user.id), class: "d-block"   do %>
        <%= fa_icon "user" %>
        <span>PROFILE</span>
        <% end %>
        <%= link_to sign_out_path, class: "d-block text-danger"  , method: :delete do %>
        <%= fa_icon "sign-out" %>
        <span>SIGN OUT</span>
        <% end %>
    </div>
</nav>

app/views/users/_user.erb
<div class="who-to-follow-person d-flex mb-1">
  <%= image_tag user.photo, class: "rounded-circle mr-1" %>
  <div class="who-to-follow-text d-block">
    <%= link_to user.fullname, user_path(user.id), class: "who-to-follow-fullname" %><br>
    <span class="last-follower"><%= last_follower(user) %></span>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container sign-up">
    <div class="sign-up-form row justify-content-center">
        <%= form_for(@user, html: { class: "col-5" }) do |f| %>
        <h4 class="text-center">Edit</h4>
        <div class="form-group">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter a username" %>
        </div>
        <div class="form-group">
            <%= f.text_field :fullname, class: "form-control", placeholder: "Enter full name" %>
        </div>
        <%= f.label :photo do %>
        Attach your profile photo
        <%= f.file_field :photo, class: "mb-3" %>
        <% end %>
        <%= f.label :cover_image do %>
        Attach your cover image (not mandatory)
        <%= f.file_field :cover_image, class: "mb-3" %>
        <% end %>
        <%= f.submit class: "btn btn-primary col-12" %>
        <p class="col-12 text-center">Already have an account? <%= link_to 'Sign in', sign_in_path %></p>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="container sign-up">
    <div class="sign-up-form row justify-content-center">
        <%= form_for(@user, html:{ class: "col-5"}) do |f| %>
        <h4 class="text-center">Sign Up</h4>
        <span class="text-danger"><%= show_errors(@user) %></span>
        <div class="form-group">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter a username" %>
        </div>
        <div class="form-group">
            <%= f.text_field :fullname, class: "form-control", placeholder: "Enter full name" %>
        </div>
        <%= f.label :photo do %>
        Attach your profile photo
        <%= f.file_field :photo, class: "mb-3" %>
        <% end %>
        <%= f.label :cover_image do %>
        Attach your cover image (not mandatory)
        <%= f.file_field :cover_image, class: "mb-3" %>
        <% end %>
        <%= f.submit class: "btn btn-primary col-12" %>
        <p class="col-12 text-center">Already have an account? <%= link_to 'Sign in', sign_in_path %></p>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="opinions-section col-9">
  <div class="cover-image-section">
    <%= image_tag  @user.cover_image, class: "cover-image"%>
  </div>
  <div class="opinions-nav opinions-nav-user">
    <%= link_to 'TWEETS', user_path(@user.id) %>
  </div>

  <div class="tweet-feed rounded mt-3 p-3">
    <h3 class="pb-3">ALL TWEETS BY <%= @user.fullname.upcase %></h3>
    <%= render @opinions %>
  </div>
</div>

<div class="right-section right-profile col">
  <div class="profile-desc text-center">
    <div class="profile-photo d-flex justify-content-center align-items-center">
      <%= followings_button(@user) %>
      <%= image_tag @user.photo, class: "rounded-circle mx-2 my-4" %>
      <%= fa_icon "list" %>
    </div>
    <span><%= link_to @user.fullname, user_path(@user.id), class: "profile-fullname text-uppercase" %></span><br>
    <span class="profile-username">@<%= @user.username %></span>
    <div class="profile-desc-counts d-flex justify-content-around align-items-center text-center mt-2 py-2">
      <div class="profile-desc-count">
        <span class="profile-desc-counter"><%= @user.opinions.count %></span><br>
        <span>Tweets</span>
      </div>
      <div class="profile-desc-count profile-desc-count-center px-2">
        <span class="profile-desc-counter"><%= @user.followeds.count %></span><br>
        <span>Following</span>
      </div>
      <div class="profile-desc-count">
        <span class="profile-desc-counter"><%= @user.followers.count %></span><br>
        <span>Followers<span>
      <div>
    </div>
  </div></div></div>
  <div class="followed-by-section">
    <h3>FOLLOWED BY</h3>
    <%= show_followers %>
  </div>
</div>